name: Publish Extension

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: vs-code
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Package extension
      run: npx vsce package
      
    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: '*.vsix'
        
    - name: Publish to VS Code Marketplace
      if: startsWith(github.ref, 'refs/tags/v')
      run: npx vsce publish --no-dependencies
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## What's Changed
          
          See the [commit history](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}) for details.
          
          ## Installation
          
          Install from the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=thelamppostdev.netlify-status) or download the `.vsix` file below and install manually.
        files: |
          *.vsix
        draft: false
        prerelease: false